import {
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiHtml5,
  SiCss3,
  SiMongodb,
} from 'react-icons/si';
import { FaSass } from 'react-icons/fa';
import { DiGit } from 'react-icons/di';

export const links = [
  {
    title: 'Javascript',
    icon: <SiJavascript />,
    bg: 'text-yellow-500',
  },
  {
    title: 'React.JS',
    icon: <SiReact />,
    url: 'https://reactjs.org/',
    key: 'ZbwW9jszKR',
    darkfg: 'text-cyan-300',
    lightfg: 'text-cyan-500',
  },
  {
    title: 'Next.JS',
    icon: <SiNextdotjs />,
    url: 'https://nextjs.org/',
    key: 'UwAWtcp3FD',
    darkfg: '',
    lightfg: '',
  },
  {
    title: 'Node.JS',
    icon: <SiNodedotjs />,
    url: 'https://nodejs.org/en/',
    key: '2L7yAiOwqv',
    darkfg: 'text-green-500',
    lightfg: 'text-green-300',
  },
  {
    title: 'Express.JS',
    icon: <SiExpress />,
    url: 'https://expressjs.com/',
    key: '0U1Zg67Wwu',
    darkfg: 'text-purple-500',
    lightfg: '',
  },
  {
    title: 'HTML5',
    icon: <SiHtml5 />,
    url: 'https://developer.mozilla.org/en-US/docs/Glossary/HTML5',
    key: '7ztkCqAL9t',
    darkfg: 'text-red-500',
    lightfg: 'text-red-300',
  },
  {
    title: 'CSS3',
    icon: <SiCss3 />,
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    key: 'idncGpTLlb',
    darkfg: 'text-blue-500',
    lightfg: 'text-blue-300',
  },
  {
    title: 'Sass',
    icon: <FaSass />,
    url: 'https://sass-lang.com/',
    key: 'Iz3dpc7C9J',
    darkfg: 'text-pink-500',
    lightfg: 'text-pink-300',
  },
  {
    title: 'Git',
    icon: <DiGit />,
    url: 'https://git-scm.com/',
    key: '9BVwD0IZrc',
    darkfg: 'text-red-500',
    lightfg: 'text-red-500',
  },
  {
    title: 'MongoDB',
    icon: <SiMongodb />,
    url: 'https://www.mongodb.com/',
    key: '6qqzsZf2zZ',
    darkfg: 'text-teal-500',
    lightfg: 'text-teal-300',
  },
];
